
#web: rails server		#command to start server
web: sudo service apache2 restart
#worker: rake data_generate	#command to start data generate sidekiq worker
#worker: rake data_analyze	#command to start data analyze sidekiq worker
worker: redis-server		#command to start redis server
